In [2]:
import numpy as np

In [3]:
# Create a 3x3 matrix
matrix = a = np.arange(15).reshape(3, 5)

# Print the matrix
print(matrix)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [4]:
matrix.shape

(3, 5)

In [5]:
rg = np.random.default_rng(1)
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))

print(a)
print(b)

[[1 1 1]
 [1 1 1]]
[[0.51182162 0.9504637  0.14415961]
 [0.94864945 0.31183145 0.42332645]]
