In [2]:
import numpy as np

In [3]:
# Crear dos arrays unidimensionales
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Concatenar los dos arrays unidimensionales
concatenated_arr = np.concatenate((arr1, arr2))
print(concatenated_arr)
# Salida: [1 2 3 4 5 6]


[1 2 3 4 5 6]


In [4]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print(np.concatenate((a, b), axis=0))
# array([[1, 2],
#        [3, 4],
#        [5, 6]])
print(np.concatenate((a, b.T), axis=1))
# array([[1, 2, 5],
#        [3, 4, 6]])
print(np.concatenate((a, b), axis=None))
# array([1, 2, 3, 4, 5, 6])

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]
[1 2 3 4 5 6]


In [16]:
import numpy as np

# Crear una matriz de 4x3
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

# Dividir la matriz en dos subarrays a lo largo del eje vertical
subarrays = np.vsplit(matrix, 2)
for subarray in subarrays:
    print(subarray)
# Salida:
# [[1 2 3]
#  [4 5 6]]
# [[ 7  8  9]
#  [10 11 12]]


[[1 2]
 [7 8]]
[[ 3  4]
 [ 9 10]]
[[ 5  6]
 [11 12]]


In [17]:
x = np.arange(8.0)
np.split(x, [3, 5, 6, 10])
# [array([0.,  1.,  2.]),
#  array([3.,  4.]),
#  array([5.]),
#  array([6.,  7.]),
#  array([], dtype=float64)]

[array([0., 1., 2.]),
 array([3., 4.]),
 array([5.]),
 array([6., 7.]),
 array([], dtype=float64)]