In [2]:
import numpy as np

In [3]:
# Crear dos arrays unidimensionales
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Concatenar los dos arrays unidimensionales
concatenated_arr = np.concatenate((arr1, arr2))
print(concatenated_arr)
# Salida: [1 2 3 4 5 6]


[1 2 3 4 5 6]


In [4]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print(np.concatenate((a, b), axis=0))
# array([[1, 2],
#        [3, 4],
#        [5, 6]])
print(np.concatenate((a, b.T), axis=1))
# array([[1, 2, 5],
#        [3, 4, 6]])
print(np.concatenate((a, b), axis=None))
# array([1, 2, 3, 4, 5, 6])

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]
[1 2 3 4 5 6]
