In [2]:
import numpy as np

In [3]:
# Create a 3x3 matrix
matrix = a = np.arange(15).reshape(3, 5)

# Print the matrix
print(matrix)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [4]:
matrix.shape

(3, 5)

In [5]:
rg = np.random.default_rng(1)
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))

print(a)
print(b)

[[1 1 1]
 [1 1 1]]
[[0.51182162 0.9504637  0.14415961]
 [0.94864945 0.31183145 0.42332645]]


In [6]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [7]:
empty_array_3d = np.empty((3, 2, 4))
print(empty_array_3d)

[[[9.32763822e-312 9.32736242e-312 5.62548054e-119 6.10912067e-067]
  [4.27255707e+180 6.96771801e+252 7.08468655e+159 8.12555790e-096]]

 [[1.12958007e+277 9.60674952e-037 7.01413727e-009 6.97387871e+228]
  [7.47011456e-114 5.95750259e+271 5.95915351e+271 5.43256360e-096]]

 [[1.06259729e+223 1.14489505e-095 7.16006779e-062 9.13544126e+242]
  [1.05135744e-153 2.00007403e+174 7.36191050e+223 9.31557487e-312]]]


In [8]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [9]:
import sys
np.set_printoptions(threshold=sys.maxsize)  # sys module should be imported
print(np.arange(100))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [10]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
print(A * B)     # elementwise product
# array([[2, 0],
#        [0, 4]])
print(A @ B)     # matrix product
# array([[5, 4],
#        [3, 4]])
print(A.dot(B))  # another matrix product
# array([[5, 4],
#        [3, 4]])

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


In [11]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, 3.14159264359, 3)
print(b.dtype.name)
# 'float64'
c = a + b
print(c)
# array([1.        , 2.57079633, 4.14159265])
print(c.dtype.name)
# 'float64'
d = np.exp(c * 1j)
print(d)
# array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
#        -0.54030231-0.84147098j])
print(d.dtype.name)
# 'complex128'

float64
[1.         2.57079632 4.14159264]
float64
[ 0.54030231+0.84147098j -0.84147098+0.54030231j -0.54030231-0.84147098j]
complex128


In [12]:
a = rg.random((2, 3))
print(a)
# array([[0.82770259, 0.40919914, 0.54959369],
#        [0.02755911, 0.75351311, 0.53814331]])
print(a.sum())
# 3.1057109529998157
print(a.min())
# 0.027559113243068367
print(a.max())
# 0.8277025938204418

[[0.82770259 0.40919914 0.54959369]
 [0.02755911 0.75351311 0.53814331]]
3.1057109529998157
0.027559113243068367
0.8277025938204418


In [13]:
b = np.arange(12).reshape(3, 4)
print(b)
# array([[ 0,  1,  2,  3],
#        [ 4,  5,  6,  7],
#        [ 8,  9, 10, 11]])

print(b.sum(axis=0))     # sum of each column
# array([12, 15, 18, 21])

print(b.min(axis=1))     # min of each row
# array([0, 4, 8])

print(b.cumsum(axis=1))  # cumulative sum along each row
# array([[ 0,  1,  3,  6],
#        [ 4,  9, 15, 22],
#        [ 8, 17, 27, 38]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[0 4 8]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


In [14]:
a = np.arange(10)**3
print(a)
# array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

print(a[2])
# 8

print(a[2:5])
# array([ 8, 27, 64])

# from start to position 6, exclusive, set every 2nd element to 1000
a[:6:2] = 1000
print(a)
# array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])

print(a[::-1])  # reversed a
# array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000])

for i in a:
    print(i**(1 / 3.))
# 9.999999999999998
# 1.0
# 9.999999999999998
# 3.0
# 9.999999999999998
# 4.999999999999999
# 5.999999999999999
# 6.999999999999999
# 7.999999999999999
# 8.999999999999998

[  0   1   8  27  64 125 216 343 512 729]
8
[ 8 27 64]
[1000    1 1000   27 1000  125  216  343  512  729]
[ 729  512  343  216  125 1000   27 1000    1 1000]
9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [15]:
def f(x, y):
    return 10 * x + y

b = np.fromfunction(f, (5, 4), dtype=int)
print(b)
# array([[ 0,  1,  2,  3],
#        [10, 11, 12, 13],
#        [20, 21, 22, 23],
#        [30, 31, 32, 33],
#        [40, 41, 42, 43]])

print(b[2, 3])
# 23

print(b[0:5, 1])  # cada fila de la segunda columna de b
# array([ 1, 11, 21, 31, 41])

print(b[:, 1])    # equivalente al ejemplo anterior
# array([ 1, 11, 21, 31, 41])

print(b[1:3, :])  # cada columna en la segunda y tercera fila de b
# array([[10, 11, 12, 13],
#        [20, 21, 22, 23]])

print(b[-1])   # the last row. Equivalent to b[-1, :]
# array([40, 41, 42, 43])

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
23
[ 1 11 21 31 41]
[ 1 11 21 31 41]
[[10 11 12 13]
 [20 21 22 23]]
[40 41 42 43]


In [18]:
c = np.array([[[0,  1,  2],  # una matriz 3D (dos matrices 2D apiladas)
               [10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])

print(c)

# Obtener la forma de la matriz
print(c.shape)
# (2, 2, 3)

# Obtener el primer elemento de la tercera dimensión, que es una matriz 2D
print(c[1, ...])  # igual que c[1, :, :] or c[1]
# array([[100, 101, 102],
#    [110, 112, 113]])

# Obtener el segundo elemento de la primera dimensión, que es una matriz 2D
print(c[..., 2])  # same as c[:, :, 2]
# array([[2,  13],
#    [102, 113]])

[[[  0   1   2]
  [ 10  12  13]]

 [[100 101 102]
  [110 112 113]]]
(2, 2, 3)
[[100 101 102]
 [110 112 113]]
[[  2  13]
 [102 113]]


In [22]:
# Crear un array tridimensional
arr = np.array([[[0, 1], [2, 3]],
                [[4, 5], [6, 7]],
                [[8, 9], [10, 11]]])

print(arr)
print(arr.shape)

# Usar ... para seleccionar todas las dimensiones excepto la última
all_but_last = arr[..., 0]
print(all_but_last)
# Salida:
# [[ 0  2]
#  [ 4  6]
#  [ 8 10]]

# Usar ... para seleccionar la primera fila y columna de la segunda dimensión
first_two_rows = arr[:, :1, :]
print(first_two_rows)
# Salida:
# [[[ 0  1]
#   [ 2  3]]
#
#  [[ 4  5]
#   [ 6  7]]
#
#  [[ 8  9]
#   [10 11]]]


[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
(3, 2, 2)
[[ 0  2]
 [ 4  6]
 [ 8 10]]
[[[0 1]]

 [[4 5]]

 [[8 9]]]
