In [1]:
import numpy as np

In [2]:
# Create a 3x3 matrix
matrix = a = np.arange(15).reshape(3, 5)

# Print the matrix
print(matrix)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [3]:
matrix.shape

(3, 5)

In [4]:
rg = np.random.default_rng(1)
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))

print(a)
print(b)

[[1 1 1]
 [1 1 1]]
[[0.51182162 0.9504637  0.14415961]
 [0.94864945 0.31183145 0.42332645]]


In [7]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [12]:
empty_array_3d = np.empty((3, 2, 4))
print(empty_array_3d)

[[[6.23042070e-307 4.67296746e-307 1.69121096e-306 7.56602523e-307]
  [1.69119873e-306 1.02356521e-306 9.34602321e-307 2.31421398e-306]]

 [[1.37961302e-306 6.23053614e-307 1.69121639e-306 9.34613185e-307]
  [3.11525958e-307 1.69118108e-306 8.06632139e-308 1.20160711e-306]]

 [[1.69119330e-306 1.29062229e-306 1.42417222e-306 1.33512648e-306]
  [7.56596412e-307 1.06810268e-306 1.69122046e-306 8.34452777e-308]]]


In [13]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [15]:
import sys
np.set_printoptions(threshold=sys.maxsize)  # sys module should be imported
print(np.arange(100))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [18]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
print(A * B)     # elementwise product
# array([[2, 0],
#        [0, 4]])
print(A @ B)     # matrix product
# array([[5, 4],
#        [3, 4]])
print(A.dot(B))  # another matrix product
# array([[5, 4],
#        [3, 4]])

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


In [22]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, 3.14159264359, 3)
print(b.dtype.name)
# 'float64'
c = a + b
print(c)
# array([1.        , 2.57079633, 4.14159265])
print(c.dtype.name)
# 'float64'
d = np.exp(c * 1j)
print(d)
# array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
#        -0.54030231-0.84147098j])
print(d.dtype.name)
# 'complex128'

float64
[1.         2.57079632 4.14159264]
float64
[ 0.54030231+0.84147098j -0.84147098+0.54030231j -0.54030231-0.84147098j]
complex128


In [23]:
a = rg.random((2, 3))
print(a)
# array([[0.82770259, 0.40919914, 0.54959369],
#        [0.02755911, 0.75351311, 0.53814331]])
print(a.sum())
# 3.1057109529998157
print(a.min())
# 0.027559113243068367
print(a.max())
# 0.8277025938204418

[[0.82770259 0.40919914 0.54959369]
 [0.02755911 0.75351311 0.53814331]]
3.1057109529998157
0.027559113243068367
0.8277025938204418


In [24]:
b = np.arange(12).reshape(3, 4)
print(b)
# array([[ 0,  1,  2,  3],
#        [ 4,  5,  6,  7],
#        [ 8,  9, 10, 11]])

print(b.sum(axis=0))     # sum of each column
# array([12, 15, 18, 21])

print(b.min(axis=1))     # min of each row
# array([0, 4, 8])

print(b.cumsum(axis=1))  # cumulative sum along each row
# array([[ 0,  1,  3,  6],
#        [ 4,  9, 15, 22],
#        [ 8, 17, 27, 38]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[0 4 8]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]
